### ISSUE TITLE
Is not editor command

### ISSUE THREAD

**Issue by sphynx79** [weizheheng/nvim-workbench#3]
I try to use your plugin, but in Windows 10 return me this error
![image](https://user-images.githubusercontent.com/5004160/116865724-79520180-ac0a-11eb-9fcd-356da14ba8ac.png)

This is my config
let g:workbench_storage_path = getenv("HOME").'/.dotfiles/vimfiles/notes/'

But i try also whiout custom config but same problem

**Comment by weizheheng** [comment]
Hi @sphynx79 , thank you so much for your interest in this plugin, I have never tried it on Windows, but I just did a few hours ago and have just deployed a fix, can you update the plugin and see if it's working?

**Comment by ichelema** [comment]
Thanks i confirm that now work nice, but i have other question why when i toggle workbench project keep the buffer open, is better every time that open and close, save and close the buffer?

**Comment by weizheheng** [comment]
Hmm, to be honest, I am not very sure which way is better. I did go through a few other plugins which use floating window, many of them use `hide` when user click toggle. And for me, when I am building this plugin, it's easier for me to keep track of the buffer because I only create it once on startup. But auto-save when toggling the buffer sounds good, I might implement it when I am free. Does hiding the buffer causing any problems to your workflow?
