### ISSUE TITLE
Checking checkboxes introduces search

### ISSUE THREAD

**Issue by BoGGoG** [weizheheng/nvim-workbench#6]
Thanks for the plugin!

Checking checkboxes with `WorkbenchToggleCheckbox` (and also adding them with the other command) starts highlighting brackets like `foo[1]` in the code below the notes window.

My fix right now is to change the mapping to
`<Plug>WorkbenchToggleCheckbox <bar> :nohl<RETURN>`
but I guess there could be a better fix.

Thanks

**Comment by weizheheng** [comment]
@BoGGoG Hi, thanks for raising this issue, this problem has been there since the beginning, but because my current setup has the highlighting turned off by default so this is not bugging me. Recently, there are a few people raising similar issues. So I decided to spend some time and try to fix this. And I am happy to say it is fixed now. On top of that, I have combined the functionality, so that you no longer need to have a second mapping to add a checkbox. By calling the mapping below, it will either add or toggle the checkbox on that line.

```vim
nmap <leader><CR> <Plug>WorkbenchToggleCheckbox
```

I have just deployed the fixes, can you try updating the plugin and see if it works? If you don't mind, I would love to hear some feedback from you about the plugin. Have a great day.

**Comment by BoGGoG** [comment]
@marcushwz cool, thank you! Works for me.

Feedback: The plugin does exactly what I was searching for and I love that it works project specific! Not sure what else I would want. Great job =)

If you are looking for more features, maybe automatically adding `TODO` etc from the code, similar to [this plugin](https://www.reddit.com/r/neovim/comments/nbh8ik/todo_comments_highlight_list_and_search_todo/) (I also found yours on Reddit I think), but I don't know how useful that would be.
